@protocol=http://
@host=100.25.136.194
@port=:4000
@prefix=/admin
@baseUrl={{protocol}}{{host}}{{port}}{{prefix}}

### Get all events

GET {{baseUrl}}/events

### Creation of an event

POST {{baseUrl}}/events
Content-Type: application/json

{
  "title": "Fête de l'Huma",
  "start_date": "2021-07-19 08:00:00",
  "end_date": "2021-07-24 08:00:00",
  "color": "#fefefe",
  "user_id": "1",
  "address_id": "1"
}

### Edit an event

PATCH {{baseUrl}}/events/5
Content-Type: application/json

{
  "title": "Fête de l'Huma",
  "start_date": "2022-09-10 08:00:00",
  "end_date": "2022-09-15 08:00:00",
  "color": "#f0f",
  "user_id": "1",
  "address_id": "1"
}

### Delete an event

DELETE {{baseUrl}}/events/4

### Get an event by its id

GET {{baseUrl}}/events/5

### Check login

POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "bo@gmail.com",
    "password": "micdrop"
}

### Creation of an user

POST {{baseUrl}}/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJpYXQiOjE2MjgwODU2MzQsImV4cCI6MTYyODExNDQzNH0.5vvXy8FTNVR9efg6OjxHK3QaZrJe5jYDyjB3f1hdEHM
Content-Type: application/json

{
  "lastname": "Obama",
  "firstname": "Michel",
  "phone_number": "0674965896",
  "role": "cdp",
  "email": "mo@gmail.com",
  "password": "micdrop",
  "status": "intermittent",
  "birth_date": "1962-12-02",
  "birth_city": "Auxerre",
  "birth_department": "89",
  "ssn": "2 62 12 89 449 491 84",
  "intermittent_registration": "1012",
  "legal_entity": null,
  "siret": null,
  "emergency_contact": "Pierre Dupont",
  "emergency_phone_number": "0612121212",
  "comments": "ne s'entend pas avec Jean-Jacques",
  "address_id":8
}

### Get all users

GET {{baseUrl}}/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJpYXQiOjE2MjgwODU2MzQsImV4cCI6MTYyODExNDQzNH0.5vvXy8FTNVR9efg6OjxHK3QaZrJe5jYDyjB3f1hdEHM

### Get all users with job

GET {{baseUrl}}/usersjob
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJpYXQiOjE2MjgwODU2MzQsImV4cCI6MTYyODExNDQzNH0.5vvXy8FTNVR9efg6OjxHK3QaZrJe5jYDyjB3f1hdEHM


### Get one user with job

GET {{baseUrl}}/usersjob/40
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJpYXQiOjE2MjgwODU2MzQsImV4cCI6MTYyODExNDQzNH0.5vvXy8FTNVR9efg6OjxHK3QaZrJe5jYDyjB3f1hdEHM


### Get all users' salary

GET {{baseUrl}}/userssalary
Content-Type: application/json

{
  "start_date": "2021-07-20",
  "end_date": "2021-07-25"
}

### Get an user by his id

GET {{baseUrl}}/users/15

### Delete an user by his id

DELETE {{baseUrl}}/users/14

### Update an user

PATCH {{baseUrl}}/users/15
Content-Type: application/json

{
  "lastname": "Obama",
  "firstname": "Michele",
  "phone_number": "0674965896",
  "role": "tech",
  "email": "bo@gmail.com",
  "password": "micdrop",
  "status": "intermittent",
  "birth_date": "1962-12-02",
  "birth_city": "Auxerre",
  "birth_department": "89",
  "ssn": "2 62 12 89 449 491 84",
  "intermittent_registration": "1012",
  "legal_entity": null,
  "siret": null,
  "emergency_contact": "Pierre Dupont",
  "emergency_phone_number": "0612121212",
  "comments": "ne s'entend pas avec Jean-Jacques ni michel d'ailleurs, mais bosse super bien avec Jean Eudes !"
}

### Get a user's planning

GET {{baseUrl}}/users/planning

### Get users by type

GET {{baseUrl}}/users/son

### Get available users

GET {{baseUrl}}/available_users

### Get available users by type

GET {{baseUrl}}/available_users/son

### Get all phases

GET {{baseUrl}}/phases

### Creation of a phase

POST {{baseUrl}}/phases
Content-Type: application/json

{
  "title": "Débrief",
  "start_date": "2021-07-26 14:00:00",
  "end_date": "2021-07-26 18:00:00",
  "type": "montage",
  "internal_location": "salle du fond",
  "tech_manager_contact": "Céline",
  "provider_contact": "Robert B",
  "number_fee": 1,
  "comments": "",
  "event_id" : 12,
  "vehicle_id": null,
  "user_id": 1
}

### Get a phase by id

GET {{baseUrl}}/phases/5

### Delete a phase

DELETE {{baseUrl}}/phases/4

### Update a phase

PATCH {{baseUrl}}/phases/5
Content-Type: application/json

{
  "title": "montage-scène principale",
  "start_date": "2021-09-09 08:00:00",
  "end_date": "2021-09-09 16:00:00",
  "type": "montage",
  "internal_location": "scène 1",
  "tech_manager_contact": "Céline",
  "provider_contact": "Robert B",
  "number_fee": 1,
  "comments": "Attention, il faudrait prévoir des parpaing pour caler la scène",
  "event_id" : 1,
  "vehicle_id": 1,
  "user_id": 1
}

### Assign a tech to a phase

POST {{baseUrl}}/phases/13/assign
Content-Type: application/json

{
  "tech_id": "14",
  "salary": "100"
}

### Get all address

GET {{baseUrl}}/address

### Creation of an address

POST {{baseUrl}}/address
Content-Type: application/json

{
  "main": "Rue de la Soif",
  "additional": null,
  "zip_code": "35000",
  "city": "Rennes"
}

### Edit an address

PATCH {{baseUrl}}/address/21
Content-Type: application/json

{
  "main": "Chez ouat",
  "additional": null,
  "zip_code": "28000",
  "city": "Toulouse"
}

### Delete an address

DELETE {{baseUrl}}/address/23