@protocol=http://
@host=localhost
@port=:4000
@prefix=/v1
@baseUrl={{protocol}}{{host}}{{port}}{{prefix}}

### Get all events

GET {{baseUrl}}/events


### vérification du login

POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "bo@gmail.com",
    "password": "micdrop"
}

### Création d'un user

POST {{baseUrl}}/users
Content-Type: application/json

{
  "lastname": "Obama",
  "firstname": "Barack",
  "phone_number": "0674965896",
  "role": "tech",
  "email": "bo@gmail.com",
  "password": "micdrop",
  "status": "intermittent",
  "birth_date": "1962-12-02",
  "birth_city": "Auxerre",
  "birth_department": "89",
  "ssn": "1 62 12 89 449 491 84",
  "intermittent_registration": "1012",
  "legal_entity": "",
  "siret": "",
  "emergency_contact": "Pierre Dupont",
  "emergency_phone_number": "0612121212",
  "comments": "ne s'entend pas avec Jean-Jacques"
}